import type { ValidationIssue } from "@/modules/shared/types";

export type InvoiceNumberRecord = {
  id: string;
  workspaceId: string;
  invoiceNumber: string;
};

export type InvoiceNumberDraft = {
  invoiceNumber: string;
  autoGenerated: boolean;
  editable: boolean;
};

export function buildNextInvoiceNumber(
  params: {
    workspaceId: string;
    invoicePrefix?: string | null;
    invoices: InvoiceNumberRecord[];
    minimumDigits?: number;
  }
): InvoiceNumberDraft {
  const workspaceInvoices = params.invoices.filter((invoice) => invoice.workspaceId === params.workspaceId);
  const prefix = params.invoicePrefix?.trim();

  if (!prefix) {
    return {
      invoiceNumber: "",
      autoGenerated: false,
      editable: true
    };
  }

  const nextSequence = Math.max(0, ...workspaceInvoices.map((invoice) => parsePrefixedSequence(invoice.invoiceNumber, prefix))) + 1;
  const digits = params.minimumDigits ?? 3;

  return {
    invoiceNumber: `${prefix}${String(nextSequence).padStart(digits, "0")}`,
    autoGenerated: true,
    editable: true
  };
}

export function validateInvoiceNumber(
  params: {
    workspaceId: string;
    invoiceNumber: string;
    invoices: InvoiceNumberRecord[];
    currentInvoiceId?: string;
  }
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const invoiceNumber = params.invoiceNumber.trim();

  if (!params.workspaceId.trim()) {
    issues.push({ severity: "blocker", code: "invoice-workspace", message: "Workspace is required." });
  }
  if (!invoiceNumber) {
    issues.push({ severity: "blocker", code: "invoice-number", message: "Invoice number is required." });
  }

  const duplicate = params.invoices.some(
    (invoice) =>
      invoice.workspaceId === params.workspaceId &&
      invoice.invoiceNumber.trim().toLowerCase() === invoiceNumber.toLowerCase() &&
      invoice.id !== params.currentInvoiceId
  );

  if (duplicate) {
    issues.push({
      severity: "blocker",
      code: "invoice-number-duplicate",
      message: "Invoice number must be unique within this workspace."
    });
  }

  return issues;
}

function parsePrefixedSequence(invoiceNumber: string, prefix: string): number {
  if (!invoiceNumber.startsWith(prefix)) {
    return 0;
  }

  const suffix = invoiceNumber.slice(prefix.length);
  return /^\d+$/.test(suffix) ? Number.parseInt(suffix, 10) : 0;
}
