import { describe, expect, it } from "vitest";
import { buildNextInvoiceNumber, validateInvoiceNumber } from "./invoiceNumbering";

describe("invoice numbering", () => {
  it("generates the next editable invoice number from the workspace prefix", () => {
    const draft = buildNextInvoiceNumber({
      workspaceId: "workspace-a",
      invoicePrefix: "EXC-",
      invoices: [
        { id: "invoice-1", workspaceId: "workspace-a", invoiceNumber: "EXC-001" },
        { id: "invoice-2", workspaceId: "workspace-a", invoiceNumber: "EXC-009" },
        { id: "invoice-other", workspaceId: "workspace-b", invoiceNumber: "EXC-050" }
      ]
    });

    expect(draft).toEqual({
      invoiceNumber: "EXC-010",
      autoGenerated: true,
      editable: true
    });
  });

  it("allows manual entry for the first invoice when no prefix exists", () => {
    const draft = buildNextInvoiceNumber({
      workspaceId: "workspace-a",
      invoicePrefix: "",
      invoices: []
    });

    expect(draft).toEqual({
      invoiceNumber: "",
      autoGenerated: false,
      editable: true
    });
  });

  it("blocks duplicate invoice numbers within the same workspace only", () => {
    const issues = validateInvoiceNumber({
      workspaceId: "workspace-a",
      invoiceNumber: "exc-001",
      invoices: [
        { id: "invoice-1", workspaceId: "workspace-a", invoiceNumber: "EXC-001" },
        { id: "invoice-other", workspaceId: "workspace-b", invoiceNumber: "EXC-001" }
      ]
    });

    expect(issues).toContainEqual(
      expect.objectContaining({ severity: "blocker", code: "invoice-number-duplicate" })
    );

    expect(
      validateInvoiceNumber({
        workspaceId: "workspace-a",
        invoiceNumber: "EXC-001",
        currentInvoiceId: "invoice-1",
        invoices: [{ id: "invoice-1", workspaceId: "workspace-a", invoiceNumber: "EXC-001" }]
      })
    ).not.toContainEqual(expect.objectContaining({ code: "invoice-number-duplicate" }));
  });
});
